# .woodpecker.yml
# Pipeline Woodpecker CI para monorepo com execução seletiva baseada em arquivos alterados.
# Sintaxe validada conforme a documentação oficial: https://woodpecker-ci.org/docs/usage/steps/

pipeline:
  install-dependencies:
    image: node:21-alpine
    commands:
      - pnpm install

  lint-api:
    depends_on: [install-dependencies]
    image: node:21-alpine
    commands:
      - pnpm --filter api lint
    when:
      changed_files:
        include:
          - apps/api/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  test-api:
    depends_on: [lint-api]
    image: node:21-alpine
    commands:
      - pnpm --filter api test
    when:
      changed_files:
        include:
          - apps/api/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  build-api:
    depends_on: [test-api]
    image: node:21-alpine
    commands:
      - pnpm --filter api build
    when:
      changed_files:
        include:
          - apps/api/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  lint-web:
    depends_on: [install-dependencies]
    image: node:21-alpine
    commands:
      - pnpm --filter botmaster-web lint
    when:
      changed_files:
        include:
          - apps/web/**
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  test-web:
    depends_on: [lint-web]
    image: node:21-alpine
    commands:
      - pnpm --filter botmaster-web test
    when:
      changed_files:
        include:
          - apps/web/**
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  build-web:
    depends_on: [test-web]
    image: node:21-alpine
    commands:
      - pnpm --filter botmaster-web build
    when:
      changed_files:
        include:
          - apps/web/**
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  lint-docs:
    depends_on: [install-dependencies]
    image: node:21-alpine
    commands:
      - pnpm --filter docs lint
    when:
      changed_files:
        include:
          - apps/docs/**
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  build-docs:
    depends_on: [lint-docs]
    image: node:21-alpine
    commands:
      - pnpm --filter docs build
    when:
      changed_files:
        include:
          - apps/docs/**
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**

  lint-ui:
    depends_on: [install-dependencies]
    image: node:21-alpine
    commands:
      - pnpm --filter @repo/ui lint
    when:
      changed_files:
        include:
          - packages/ui/**
          - packages/eslint-config/**
          - packages/typescript-config/**