when:
  event:
    - pull_request
    - push

steps:
  - name: install-dependencies
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm install

  - name: lint-and-format
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run lint:all
      - pnpm run format:all

  - name: testing
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run test
      - pnpm run test:affected
      - pnpm run test:coverage

  - name: security
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run security:scan

  - name: bundle-analysis
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run bundle:analyze