steps:
  install-dependencies:
    image: node:20
    commands:
      - npm i -g pnpm
      - pnpm i
    when:
      event: [ pull_request, push ]

  bundle-analyze:
    image: node:21.6.2-alpine
    commands:
      - pnpm run bundle:analyze
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  lint:
    image: node:20
    commands:
      - pnpm lint
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  format-check:
    image: node:20
    commands:
      - pnpm format:check
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  security-scan:
    image: node:20
    commands:
      - pnpm audit
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  test:
    image: node:20
    commands:
      - pnpm test
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  test-affected:
    image: node:20
    commands:
      - pnpm test:affected
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]

  test-coverage:
    image: node:20
    commands:
      - pnpm test:coverage
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]