when:
  event:
    - pull_request
    - push

steps:
  - name: install-dependencies
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm install

include:
  - .woodpecker/lint.yml
  - .woodpecker/test.yml
  - .woodpecker/security.yml
  - .woodpecker/bundle-analysis.yml