DROP INDEX IF EXISTS idx_installed_worker_worker_id;
DROP INDEX IF EXISTS idx_installed_worker_machine_id;
DROP INDEX IF EXISTS idx_installed_worker_status;
DROP INDEX IF EXISTS idx_installed_worker_folder_key;
DROP INDEX IF EXISTS idx_installed_worker_priority;
DROP INDEX IF EXISTS idx_installed_worker_installed_at;
DROP INDEX IF EXISTS idx_installed_worker_installed_by;
DROP INDEX IF EXISTS idx_installed_worker_default_version;
DROP TABLE IF EXISTS installed_worker;
