DROP INDEX IF EXISTS idx_worker_installation_worker_id;
DROP INDEX IF EXISTS idx_worker_installation_machine_id;
DROP INDEX IF EXISTS idx_worker_installation_status;
DROP INDEX IF EXISTS idx_worker_installation_folder_key;
DROP INDEX IF EXISTS idx_worker_installation_priority;
DROP INDEX IF EXISTS idx_worker_installation_installed_at;
DROP INDEX IF EXISTS idx_worker_installation_installed_by;
DROP INDEX IF EXISTS idx_worker_installation_default_version;
DROP TABLE IF EXISTS worker_installation;
