when:
  event:
    - pull_request
    - push
    - commit

steps:
  - name: bundle-analyze
    depends_on: [ install-dependencies ]
    image: node:21.6.2-alpine
    commands:
      - pnpm run bundle:analyze