steps:
  - name: bundle-analysis
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run bundle:analyze
    when:
      event:
        - pull_request
        - push