pipeline:
  install-dependencies:
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
    when:
      event:
        - push
        - pull_request

  lint-and-format:
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm run lint:all
      - pnpm run format:all
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request

  test:
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm run test:ci
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request

  security:
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm run security:scan
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request

  bundle-analysis:
    image: node:21.6.2-alpine
    commands:
      - corepack enable
      - pnpm run bundle:analyze
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request