pipeline:
  install-dependencies:
    image: node:21.6.2-alpine
    commands:
      - npm i -g pnpm@8.15.6
      - pnpm install
    when:
      event:
        - pull_request
        - push
        - commit
