steps:
  lint:
    image: node:20
    commands:
      - pnpm lint
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]
  format-check:
    image: node:20
    commands:
      - pnpm format:check
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]