when:
  event:
    - pull_request
    - push
    - commit

steps:
  - name: security-scan
    depends_on: [ install-dependencies ]
    image: node:21.6.2-alpine
    commands:
      - pnpm run security:scan