when:
  event:
    - pull_request
    - push
    - commit
  depends_on:
    - install-dependencies

steps:
  - name: test
    image: node:21.6.2-alpine
    commands:
      - pnpm run test

  - name: test-affected
    image: node:21.6.2-alpine
    commands:
      - pnpm run test:affected

  - name: test-coverage
    image: node:21.6.2-alpine
    commands:
      - pnpm run test:coverage
