steps:
  test:
    image: node:20
    commands:
      - pnpm test
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]
  test-affected:
    image: node:20
    commands:
      - pnpm test:affected
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]
  test-coverage:
    image: node:20
    commands:
      - pnpm test:coverage
    depends_on:
      - install-dependencies
    when:
      event: [ pull_request, push ]