steps:
  - name: testing
    image: node:21.6.2-alpine
    depends_on:
      - install-dependencies
    commands:
      - corepack enable
      - pnpm run test
      - pnpm run test:affected
      - pnpm run test:coverage
    when:
      event:
        - pull_request
        - push